AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  testAWSSAM

  Sample SAM Template for testAWSSAM

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      Enviroment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref ConversationTable
          OPENAI_API_KEY_SECRET_NAME: "prod/testAWSSAM/test-key"
          AWS_REGION_NAME: !Ref AWS::Region
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: 
                !Sub "arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:prod/testAWSSAM/test-key-3N5hAV"
        - DynamoDBCrudPolicy: 
            TableName: !Ref ConversationTable 
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
            RestApiId: !Ref AIChatroomApiGateway
        PostMessage:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /message
            Method: post
            RestApiId: !Ref AIChatroomApiGateway

  # 顯示定義 API Gateway
  AIChatroomApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowOrigin: "'*'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api_Key,X-Amz-Security-Token'"
        AllowMethods: "'GET,POST,OPTIONS'"

  # 定義 DynamoDB 表
  ConversationTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "AIChatroomConversations-${AWS::StackName}"
      AttributeDefinitions: # 屬性定義
        - AttributeName: conversation_id
          AttributeType: S # String
      KeySchema: # 主鍵定義
        - AttributeName: conversation_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST # 按需計費模式 (On-demand)

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${AIChatroomApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
  AIChatroomTableArn:
    Description: "DynamoDB Conversation Table ARN"
    Value: !GetAtt ConversationTable.Arn
